package com.wechat.auto.mapper;

import com.wechat.auto.model.PostKeyword;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PostKeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywordTable
     *
     * @mbggenerated
     */
    @Delete({
        "delete from keywordTable",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywordTable
     *
     * @mbggenerated
     */
    @Insert({
        "insert into keywordTable (id, wordtext, ",
        "wordfrequency, wordtype)",
        "values (#{id,jdbcType=INTEGER}, #{wordtext,jdbcType=VARCHAR}, ",
        "#{wordfrequency,jdbcType=INTEGER}, #{wordtype,jdbcType=INTEGER})"
    })
    int insert(PostKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywordTable
     *
     * @mbggenerated
     */
    int insertSelective(PostKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywordTable
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, wordtext, wordfrequency, wordtype",
        "from keywordTable",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    PostKeyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywordTable
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PostKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywordTable
     *
     * @mbggenerated
     */
    @Update({
        "update keywordTable",
        "set wordtext = #{wordtext,jdbcType=VARCHAR},",
          "wordfrequency = #{wordfrequency,jdbcType=INTEGER},",
          "wordtype = #{wordtype,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PostKeyword record);

    @Select({
            "select",
            "id, wordtext, wordfrequency, wordtype",
            "from keywordTable",
            "where wordtext = #{wordtext,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    PostKeyword selectKeyWord(@Param("wordtext") String wordtext);

    @Select({
            "select",
            "id, wordtext, wordfrequency, wordtype",
            "from keywordTable",
            "where wordtype = #{wordtype,jdbcType=INTEGER}",
            "order by wordfrequency DESC"
    })
    @ResultMap("BaseResultMap")
    List<PostKeyword> selectAllKeyWord(@Param("wordtype") Integer wordtype);

    @Delete({
            "delete from keywordTable"
    })
    int deleteAll();
}