package com.wechat.auto.model;

import java.util.Date;

public class WechatPost {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postTable.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postTable.biz
     *
     * @mbggenerated
     */
    private String biz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postTable.appmsgid
     *
     * @mbggenerated
     */
    private String appmsgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postTable.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postTable.digest
     *
     * @mbggenerated
     */
    private String digest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postTable.contenturl
     *
     * @mbggenerated
     */
    private String contenturl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postTable.sourceurl
     *
     * @mbggenerated
     */
    private String sourceurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postTable.cover
     *
     * @mbggenerated
     */
    private String cover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postTable.datetime
     *
     * @mbggenerated
     */
    private Date datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postTable.readnum
     *
     * @mbggenerated
     */
    private Integer readnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postTable.likenum
     *
     * @mbggenerated
     */
    private Integer likenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postTable.isspider
     *
     * @mbggenerated
     */
    private Integer isspider;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postTable.author
     *
     * @mbggenerated
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postTable.nickname
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postTable.weight
     *
     * @mbggenerated
     */
    private Integer weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postTable.posttype
     *
     * @mbggenerated
     */
    private Integer posttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column postTable.content
     *
     * @mbggenerated
     */
    private String content;

    public WechatPost(){}
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postTable
     *
     * @mbggenerated
     */
    public WechatPost(Integer id, String biz, String appmsgid, String title, String digest, String contenturl, String sourceurl, String cover, Date datetime, Integer readnum, Integer likenum, Integer isspider, String author, String nickname, Integer weight, Integer posttype, String content) {
        this.id = id;
        this.biz = biz;
        this.appmsgid = appmsgid;
        this.title = title;
        this.digest = digest;
        this.contenturl = contenturl;
        this.sourceurl = sourceurl;
        this.cover = cover;
        this.datetime = datetime;
        this.readnum = readnum;
        this.likenum = likenum;
        this.isspider = isspider;
        this.author = author;
        this.nickname = nickname;
        this.weight = weight;
        this.posttype = posttype;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postTable.id
     *
     * @return the value of postTable.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postTable.biz
     *
     * @return the value of postTable.biz
     *
     * @mbggenerated
     */
    public String getBiz() {
        return biz;
    }

    public void setBiz(String biz){
        this.biz = biz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postTable.appmsgid
     *
     * @return the value of postTable.appmsgid
     *
     * @mbggenerated
     */
    public String getAppmsgid() {
        return appmsgid;
    }

    public void setAppmsgid(String appmsgid){
        this.appmsgid = appmsgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postTable.title
     *
     * @return the value of postTable.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    public void setTitle(String title){
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postTable.digest
     *
     * @return the value of postTable.digest
     *
     * @mbggenerated
     */
    public String getDigest() {
        return digest;
    }

    public void setDigest(String digest){
        this.digest = digest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postTable.contenturl
     *
     * @return the value of postTable.contenturl
     *
     * @mbggenerated
     */
    public String getContenturl() {
        return contenturl;
    }

    public void setContenturl(String contenturl){
        this.contenturl = contenturl;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postTable.sourceurl
     *
     * @return the value of postTable.sourceurl
     *
     * @mbggenerated
     */
    public String getSourceurl() {
        return sourceurl;
    }

    public void setSourceurl(String sourceurl){
        this.sourceurl = sourceurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postTable.cover
     *
     * @return the value of postTable.cover
     *
     * @mbggenerated
     */
    public String getCover() {
        return cover;
    }

    public void setConver(String cover){
        this.cover = cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postTable.datetime
     *
     * @return the value of postTable.datetime
     *
     * @mbggenerated
     */
    public Date getDatetime() {
        return datetime;
    }

    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postTable.readnum
     *
     * @return the value of postTable.readnum
     *
     * @mbggenerated
     */
    public Integer getReadnum() {
        return readnum;
    }

    public void setReadnum(Integer readnum){
        this.readnum = readnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postTable.likenum
     *
     * @return the value of postTable.likenum
     *
     * @mbggenerated
     */
    public Integer getLikenum() {
        return likenum;
    }

    public void setLikenum(Integer likenum){
        this.likenum = likenum;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postTable.isspider
     *
     * @return the value of postTable.isspider
     *
     * @mbggenerated
     */
    public Integer getIsspider() {
        return isspider;
    }

    public void setIsspider(Integer isspider){
        this.isspider = isspider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postTable.author
     *
     * @return the value of postTable.author
     *
     * @mbggenerated
     */
    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author){
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postTable.nickname
     *
     * @return the value of postTable.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname){
        this.nickname = nickname;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postTable.weight
     *
     * @return the value of postTable.weight
     *
     * @mbggenerated
     */
    public Integer getWeight() {
        return weight;
    }

    public void setWeight(Integer weight){
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postTable.posttype
     *
     * @return the value of postTable.posttype
     *
     * @mbggenerated
     */
    public Integer getPosttype() {
        return posttype;
    }

    public void setPosttype(Integer posttype){
        this.posttype = posttype;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column postTable.content
     *
     * @return the value of postTable.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    public void setContent(String content){
        this.content = content;
    }

    public void setIsspider(int isspider){
        this.isspider = isspider;
    }
}